apiVersion: v1
kind: Service
metadata:
  name: rhokp-mcp
  labels:
    app: rhokp-mcp
spec:
  type: ClusterIP
  selector:
    app: rhokp-mcp
  ports:
    - name: mcp
      port: 8000
      protocol: TCP
      targetPort: 8000
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
