apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: openshift-kueue-operator-group
  namespace: openshift-kueue-operator
  annotations:
    olm.providedAPIs: Kueue.v1.kueue.openshift.io
    argocd.argoproj.io/sync-wave: "2"
spec: {}
